### ISSUE TITLE
Documentazione

### ISSUE THREAD

**Issue by libremente** [ProvinciaAutonomaTrento/PITre#1]
Buongiorno,

in questo momento il validatore del publiccode fallisce sui campi `documentation` e `apiDocumentation`. Infatti, le URL indicate dovrebbero puntare ad un file e non ad una directory. Se volete tenere la documentazione all'interno di queste dir vi consiglierei di fare due file di riassunto della documentazione da mettere nella root delle folder `documentation` e `documentazionePIS` e puntare la chiave verso tali file.

Ad esempio un file README inserito in `/documentation/README.md` potrebbe elencare la serie di file di documentazione contenuti in tale cartella.

Resto a disposizione.
Grazie @marcomb

**Comment by marcomb** [comment]
Vero, mi scuso. Ho creato due README semplici che elencano la documentazione, e li ho linkati dal YML.  Ora dovrebbe questo problema essere risolto

Si tratta di un primo rilascio, diversi dettagli sono migliorabili, ma volevamo comunque esporre nel catalogo cio che gia in pratica è stato condiviso mediante altri supporti media, e preso a riuso gia da diverse PA.

**Comment by libremente** [comment]
Perfetto!
Grazie molte!
Il file publiccode.yml "vive" nel repo con il resto dei sorgenti e quindi potrà ovviamente migliorare nel tempo. 
Resto a disposizione

**Comment by libremente** [comment]
Fixed by https://github.com/ProvinciaAutonomaTrento/PITre/commit/77c353a299fd1bdb89e71178bb1310cdb35f2e9b, closing. Grazie molte @marcomb
